Refactor to support configurations and single entry script
mlimaloureiro/ansible-maas-dynamic-inventory pull request #8
Opened 2018-09-20 14:08 UTC by fsschmitt

- Add configparser support
- Add .ini configuration file
- Add configuration fallback with defaults
- Refactor to support configuration and cli arguments to be expandable 
- Refactor to support group_by functionality based on configuration
- Update test to support single entry script
- Update README.md to support single entry script
- Update README.md to include configuration specs

2018-09-24 16:25 UTC, mlimaloureiro requested changes

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.ini
> +cache_max_age = 300
new line

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +    "cache_max_age": 300
cache_max_age_in_{wtv is the unit}

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        ''' Command line argument processing '''
what was the reason to remove click ?

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        return self.builder.build_from_machines(machines)
nl

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        return self.builder.build_from_machines(machines)
nl

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +    def _default_inventory(self) -> dict:
have the private methods in the bottom

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        if self.args.refresh_cache and os.path.isfile("{}.sqlite".format(file_name)):
why is sqlite referenced here ? is it caching in sqlite ?

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +    def read_settings(self):
this method is really big and hard to read

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        file_name = os.path.join(folder_path, "ansible-maas-dynamics-inventory")
constant for `ansible-maas-dynamic-inventory`

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        # MAAS Credentials
no need for comments, be explicit on property name instead

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +        # Read settings, parse CLI arguments and config Cache
whenever you're adding a comment to a block, it probably means you can find a better name / export to method

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +class MAASInventory(object):
just call it main() it's usually the class that can have a lot of shit there

2018-09-24 16:25 UTC, mlimaloureiro commented on maas.py
> +    def config_cache(self):
this doesn't make sense to be here, it's actually in the context of `Fetch` class as a cache provider

2018-09-24 17:28 UTC, fsschmitt commented on maas.py
> +        if self.args.refresh_cache and os.path.isfile("{}.sqlite".format(file_name)):
Yes, requests_cache by default stores cache in sqlite

2018-09-24 17:53 UTC, fsschmitt commented on maas.py
> +        ''' Command line argument processing '''
In order to use the python's standard lib [argparser](https://docs.python.org/3/library/argparse.html)

2018-09-24 17:53 UTC, fsschmitt commented on maas.py
> +    def read_settings(self):
Broken down into multiple, smaller and more specific methods.

2018-09-24 17:54 UTC, fsschmitt commented on maas.py
> +    def config_cache(self):
Moved into Fetch constructor, configured through the cache_settings variable.

2018-09-24 17:55 UTC, fsschmitt commented on maas.py
> +        file_name = os.path.join(folder_path, "ansible-maas-dynamics-inventory")
Modified to also be a configurable variable (same as path).

2018-09-25 08:13 UTC, mlimaloureiro commented on maas.py
> +        self._load_maas_settings(config)
so much better 🥇

2018-09-25 08:14 UTC, mlimaloureiro approved these changes

2018-09-25 08:15 UTC, merged